In [1]:
import pandas as pd 
import numpy as np

df_movie_final = pd.read_csv('movie_ratings_final.csv')
df_movie_final = df_movie_final.drop(columns=['Unnamed: 0', 'Unnamed: 0.1'])
df_movie_final.loc[:, 'year'] = df_movie_final['year'].str[-5:].astype(int)
df_movie_final.loc[:, 'runtime'] = df_movie_final['runtime'].str[:-3].astype(int)
df_movie_final.head()

,title,year,ageRestriction,runtime,imdbScore,metaScore,genres,directors,actors,gross,votes,link,budget
0,Star Wars: Episode VII - The Force Awakens,2015,PG-13,138,79.0,80.0,"['Action', 'Adventure', 'Sci-Fi']",['J.J. Abrams'],"['Daisy Ridley', 'John Boyega', 'Oscar Isaac',...",936662225,837432,/title/tt2488496/,$245000000
1,Avengers: Endgame,2019,PG-13,181,84.0,78.0,"['Action', 'Adventure', 'Drama']","['Anthony Russo', 'Joe Russo']","['Robert Downey Jr.', 'Chris Evans', 'Mark Ruf...",858373000,718146,/title/tt4154796/,$356000000
2,Avatar,2009,PG-13,162,78.0,83.0,"['Action', 'Adventure', 'Fantasy']",['James Cameron'],"['Sam Worthington', 'Zoe Saldana', 'Sigourney ...",760507625,1091518,/title/tt0499549/,$237000000
3,Black Panther,2018,PG-13,134,73.0,88.0,"['Action', 'Adventure', 'Sci-Fi']",['Ryan Coogler'],"['Chadwick Boseman', 'Michael B. Jordan', ""Lup...",700059566,581412,/title/tt1825683/,$200000000
4,Avengers: Infinity War,2018,PG-13,149,85.0,68.0,"['Action', 'Adventure', 'Sci-Fi']","['Anthony Russo', 'Joe Russo']","['Robert Downey Jr.', 'Chris Hemsworth', 'Mark...",678815482,774546,/title/tt4154756/,$321000000

In [2]:
# Sanitize budget for currency signs
df_movie_final = df_movie_final.drop(df_movie_final[df_movie_final['budget'].str.startswith('$') == False].index)

In [3]:
import re
listbudget = df_movie_final.budget
listCurrency = []
for ele in listbudget:
    listCurrency.append(re.compile("\d").split(ele)[0])
listCurrency
df_currency = pd.DataFrame(listCurrency, columns=["currency"])
df_currency.currency.unique()

array(['$'], dtype=object)

In [4]:
df_movie_final.loc[:, 'budget'] = df_movie_final['budget'].str.replace("$", "").astype(int)
df_movie_final.reset_index(drop=True, inplace=True)
df_movie_final.head()

,title,year,ageRestriction,runtime,imdbScore,metaScore,genres,directors,actors,gross,votes,link,budget
0,Star Wars: Episode VII - The Force Awakens,2015,PG-13,138,79.0,80.0,"['Action', 'Adventure', 'Sci-Fi']",['J.J. Abrams'],"['Daisy Ridley', 'John Boyega', 'Oscar Isaac',...",936662225,837432,/title/tt2488496/,245000000
1,Avengers: Endgame,2019,PG-13,181,84.0,78.0,"['Action', 'Adventure', 'Drama']","['Anthony Russo', 'Joe Russo']","['Robert Downey Jr.', 'Chris Evans', 'Mark Ruf...",858373000,718146,/title/tt4154796/,356000000
2,Avatar,2009,PG-13,162,78.0,83.0,"['Action', 'Adventure', 'Fantasy']",['James Cameron'],"['Sam Worthington', 'Zoe Saldana', 'Sigourney ...",760507625,1091518,/title/tt0499549/,237000000
3,Black Panther,2018,PG-13,134,73.0,88.0,"['Action', 'Adventure', 'Sci-Fi']",['Ryan Coogler'],"['Chadwick Boseman', 'Michael B. Jordan', ""Lup...",700059566,581412,/title/tt1825683/,200000000
4,Avengers: Infinity War,2018,PG-13,149,85.0,68.0,"['Action', 'Adventure', 'Sci-Fi']","['Anthony Russo', 'Joe Russo']","['Robert Downey Jr.', 'Chris Hemsworth', 'Mark...",678815482,774546,/title/tt4154756/,321000000

In [5]:
df_genres = df_movie_final['genres'].str.replace("[", "").str.replace("]", "").str.replace("'", "").str.replace("'","").str.join(sep='').str.get_dummies(sep=', ')
result = pd.concat([df_movie_final, df_genres], axis=1).reindex(df_movie_final.index)

# sanitize ageRestriction and drop unrelated columns
result = result.drop(result[result['ageRestriction']=='Unrated'].index)
result = result.drop(result[result['ageRestriction']=='Not Rated'].index)
result = result.drop(['title','directors','actors', 'genres', 'link'],'columns')

# onehot encode ageRestriction
result = pd.get_dummies(result,columns=['ageRestriction'])
result.reset_index(drop=True, inplace=True)
result.head()

,year,runtime,imdbScore,metaScore,gross,votes,budget,Action,Adventure,Animation,...,War,Western,ageRestriction_15,ageRestriction_G,ageRestriction_NC-17,ageRestriction_PG,ageRestriction_PG-13,ageRestriction_R,ageRestriction_TV-MA,ageRestriction_TV-PG
0,2015,138,79.0,80.0,936662225,837432,245000000,1,1,0,...,0,0,0,0,0,0,1,0,0,0
1,2019,181,84.0,78.0,858373000,718146,356000000,1,1,0,...,0,0,0,0,0,0,1,0,0,0
2,2009,162,78.0,83.0,760507625,1091518,237000000,1,1,0,...,0,0,0,0,0,0,1,0,0,0
3,2018,134,73.0,88.0,700059566,581412,200000000,1,1,0,...,0,0,0,0,0,0,1,0,0,0
4,2018,149,85.0,68.0,678815482,774546,321000000,1,1,0,...,0,0,0,0,0,0,1,0,0,0

In [6]:

list_profit_margin = []
for i in range(len(result)):
    list_profit_margin.append(result.gross[i] / result.budget[i])


df_profit_margin = pd.DataFrame(list_profit_margin, columns=['profit_margin'])
result = pd.concat([result, df_profit_margin], axis=1).reindex(result.index)

result.head()

,year,runtime,imdbScore,metaScore,gross,votes,budget,Action,Adventure,Animation,...,Western,ageRestriction_15,ageRestriction_G,ageRestriction_NC-17,ageRestriction_PG,ageRestriction_PG-13,ageRestriction_R,ageRestriction_TV-MA,ageRestriction_TV-PG,profit_margin
0,2015,138,79.0,80.0,936662225,837432,245000000,1,1,0,...,0,0,0,0,0,1,0,0,0,3.823111
1,2019,181,84.0,78.0,858373000,718146,356000000,1,1,0,...,0,0,0,0,0,1,0,0,0,2.411160
2,2009,162,78.0,83.0,760507625,1091518,237000000,1,1,0,...,0,0,0,0,0,1,0,0,0,3.208893
3,2018,134,73.0,88.0,700059566,581412,200000000,1,1,0,...,0,0,0,0,0,1,0,0,0,3.500298
4,2018,149,85.0,68.0,678815482,774546,321000000,1,1,0,...,0,0,0,0,0,1,0,0,0,2.114690

In [7]:
from sklearn.cluster import estimate_bandwidth

def clean_dataset(df):
    assert isinstance(df, pd.DataFrame), "df needs to be a pd.DataFrame"
    df.dropna(inplace=True)
    indices_to_keep = ~df.isin([np.nan, np.inf, -np.inf]).any(1)
    return df[indices_to_keep].astype(np.float64)

movie_data = clean_dataset(result)

eb = estimate_bandwidth(movie_data)

In [8]:
from sklearn.cluster import MeanShift
analyzer = MeanShift(bandwidth=eb) 
analyzer.fit(movie_data)

MeanShift(bandwidth=55472476.28320057, bin_seeding=False, cluster_all=True,
          min_bin_freq=1, n_jobs=None, seeds=None)

In [9]:
labels = analyzer.labels_
print(labels)
print('\n\n',np.unique(labels))

[12  8 14 ...  0  0  0]


 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

In [10]:
movie_data['cluster_group'] = np.nan
data_length=len(movie_data)
for i in range(data_length): #movie length
    movie_data.iloc[i,movie_data.columns.get_loc('cluster_group')] = labels[i] #set the cluster label on each row

movie_data.head()

,year,runtime,imdbScore,metaScore,gross,votes,budget,Action,Adventure,Animation,...,ageRestriction_15,ageRestriction_G,ageRestriction_NC-17,ageRestriction_PG,ageRestriction_PG-13,ageRestriction_R,ageRestriction_TV-MA,ageRestriction_TV-PG,profit_margin,cluster_group
0,2015.0,138.0,79.0,80.0,936662225.0,837432.0,245000000.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,3.823111,12.0
1,2019.0,181.0,84.0,78.0,858373000.0,718146.0,356000000.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,2.411160,8.0
2,2009.0,162.0,78.0,83.0,760507625.0,1091518.0,237000000.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,3.208893,14.0
3,2018.0,134.0,73.0,88.0,700059566.0,581412.0,200000000.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,3.500298,10.0
4,2018.0,149.0,85.0,68.0,678815482.0,774546.0,321000000.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,2.114690,9.0

In [11]:
movie_data.describe()

,year,runtime,imdbScore,metaScore,gross,votes,budget,Action,Adventure,Animation,...,ageRestriction_15,ageRestriction_G,ageRestriction_NC-17,ageRestriction_PG,ageRestriction_PG-13,ageRestriction_R,ageRestriction_TV-MA,ageRestriction_TV-PG,profit_margin,cluster_group
count,3394.000000,3394.000000,3394.000000,3394.000000,3.394000e+03,3.394000e+03,3.394000e+03,3394.000000,3394.000000,3394.000000,...,3394.000000,3394.000000,3394.000000,3394.000000,3394.000000,3394.000000,3394.000000,3394.000000,3394.000000,3394.000000
mean,2009.105775,107.263406,62.807012,51.468179,5.521220e+07,1.212064e+05,4.290016e+07,0.262522,0.217443,0.065999,...,0.000589,0.017678,0.000589,0.145846,0.398939,0.434001,0.002062,0.000295,4.022872,0.170301
std,5.513080,17.356685,9.794689,17.373967,8.020410e+07,1.751512e+05,4.811770e+07,0.440070,0.412567,0.248317,...,0.024271,0.131799,0.024271,0.353003,0.489752,0.495698,0.045374,0.017165,123.608976,0.781748
min,2000.000000,63.000000,14.000000,5.000000,3.880000e+02,5.100000e+01,2.500000e+03,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000056,0.000000
25%,2005.000000,94.250000,57.000000,38.000000,7.456152e+06,1.917825e+04,1.000000e+07,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.409874,0.000000
50%,2009.000000,104.000000,64.000000,51.000000,2.976337e+07,5.989400e+04,2.500000e+07,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.983597,0.000000
75%,2014.000000,117.000000,70.000000,64.000000,6.728226e+07,1.473040e+05,5.700000e+07,1.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,1.931216,0.000000
max,2020.000000,224.000000,90.000000,100.000000,9.366622e+08,2.210422e+06,3.560000e+08,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,7194.587333,14.000000

In [12]:
#Grouping movies by Cluster
movie_cluster_data = movie_data.groupby(['cluster_group']).mean()
#Count of movies in each cluster
movie_cluster_data['Counts'] = pd.Series(movie_data.groupby(['cluster_group']).size())
movie_cluster_data

,year,runtime,imdbScore,metaScore,gross,votes,budget,Action,Adventure,Animation,...,ageRestriction_15,ageRestriction_G,ageRestriction_NC-17,ageRestriction_PG,ageRestriction_PG-13,ageRestriction_R,ageRestriction_TV-MA,ageRestriction_TV-PG,profit_margin,Counts
cluster_group,,,,,,,,,,,,,,,,,,,,,
0.0,2008.925854,105.818862,62.082276,50.361301,3.517561e+07,9.105774e+04,3.249068e+07,0.230569,0.162276,0.047154,...,0.00065,0.015285,0.00065,0.129756,0.381138,0.469919,0.002276,0.000325,4.211434,3075
1.0,2010.215517,117.974138,68.732759,60.375000,1.953836e+08,3.633722e+05,1.335323e+08,0.560345,0.706897,0.258621,...,0.00000,0.043103,0.00000,0.310345,0.551724,0.094828,0.000000,0.000000,1.744287,232
2.0,2010.500000,122.533333,72.400000,66.433333,3.241284e+08,5.380424e+05,7.916000e+07,0.366667,0.700000,0.300000,...,0.00000,0.033333,0.00000,0.366667,0.400000,0.200000,0.000000,0.000000,6.023852,30
3.0,2013.000000,126.181818,73.045455,69.454545,3.968467e+08,4.798184e+05,1.784545e+08,0.636364,1.000000,0.227273,...,0.00000,0.090909,0.00000,0.227273,0.681818,0.000000,0.000000,0.000000,2.295073,22
4.0,2015.200000,122.800000,76.200000,71.000000,5.069438e+08,6.676352e+05,1.790000e+08,0.400000,0.600000,0.400000,...,0.00000,0.000000,0.00000,0.600000,0.400000,0.000000,0.000000,0.000000,2.863214,5
5.0,2012.058824,138.647059,68.823529,58.705882,2.648411e+08,4.574424e+05,2.492941e+08,0.764706,0.941176,0.058824,...,0.00000,0.000000,0.00000,0.176471,0.823529,0.000000,0.000000,0.000000,1.084639,17
6.0,2016.250000,141.250000,73.250000,63.000000,4.914964e+08,6.720352e+05,2.587500e+08,0.750000,1.000000,0.250000,...,0.00000,0.000000,0.00000,0.250000,0.750000,0.000000,0.000000,0.000000,1.898240,4
7.0,2015.000000,130.500000,78.000000,74.500000,6.159306e+08,7.323220e+05,2.100000e+08,1.000000,1.000000,0.500000,...,0.00000,0.000000,0.00000,0.500000,0.500000,0.000000,0.000000,0.000000,2.937999,2
8.0,2019.000000,181.000000,84.000000,78.000000,8.583730e+08,7.181460e+05,3.560000e+08,1.000000,1.000000,0.000000,...,0.00000,0.000000,0.00000,0.000000,1.000000,0.000000,0.000000,0.000000,2.411160,1
9.0,2018.000000,149.000000,85.000000,68.000000,6.788155e+08,7.745460e+05,3.210000e+08,1.000000,1.000000,0.000000,...,0.00000,0.000000,0.00000,0.000000,1.000000,0.000000,0.000000,0.000000,2.114690,1
10.0,2018.000000,134.000000,73.000000,88.000000,7.000596e+08,5.814120e+05,2.000000e+08,1.000000,1.000000,0.000000,...,0.00000,0.000000,0.00000,0.000000,1.000000,0.000000,0.000000,0.000000,3.500298,1
11.0,2017.000000,152.000000,70.000000,84.000000,6.201814e+08,5.386460e+05,3.170000e+08,1.000000,1.000000,0.000000,...,0.00000,0.000000,0.00000,0.000000,1.000000,0.000000,0.000000,0.000000,1.956408,1
12.0,2015.000000,138.000000,79.000000,80.000000,9.366622e+08,8.374320e+05,2.450000e+08,1.000000,1.000000,0.000000,...,0.00000,0.000000,0.00000,0.000000,1.000000,0.000000,0.000000,0.000000,3.823111,1
13.0,2015.000000,124.000000,70.000000,59.000000,6.522706e+08,5.633090e+05,1.500000e+08,1.000000,1.000000,0.000000,...,0.00000,0.000000,0.00000,0.000000,1.000000,0.000000,0.000000,0.000000,4.348471,1
14.0,2009.000000,162.000000,78.000000,83.000000,7.605076e+08,1.091518e+06,2.370000e+08,1.000000,1.000000,0.000000,...,0.00000,0.000000,0.00000,0.000000,1.000000,0.000000,0.000000,0.000000,3.208893,1

# Konklusion

###### Vi fravælger alle urelevante cluster hvor antallet af film er under 10. Hermed har vi følgende cluster tilbage som vi vil analysere: 0, 1, 2, 3 og 5.
Vi kan på baggrund konkludere nogle forskellige ting. 
    - til at starte med, så er vores hoved
* Cluster 0
    * Består af 3075 film
    * Profit margin på 4,230532 - Profit Margen for de fleste film er umiddelbart 4 gange budgettet
    * PG-13, ageRestriction_R
    * Top 3 genre: Comedy, Drama, Action
    * Udgivelsesår: 2009
    * Spilletid: 162 min
    * imdbScore: 78
    * MetaScore : 83
    * Indtjening: \\$35.175.610
    * Budget: \\$32.490.680
 
* Cluster 1
    * Består af 232 film
    * Profit margin på 1,744287
    * PG-13, ageRestriction_PG
    * Top 3 genre: Action, Adventure, Comedy
    * Udgivelsesår: 2010
    * Spilletid: 117 min
    * imdbScore: 
    * MetaScore : 60
    * Indtjening: \\$195.383.600
    * Budget: \\$133.532.300

* Cluster 2
    * Består af 30 film
    * Profit margin på 6,023852
    * PG-13, ageRestriction_PG
    * Top 3 genre: Adventure, Comedy, Action
    * Udgivelsesår: 2010
    * Spilletid: 122 min
    * imdbScore: 72
    * MetaScore : 66
    * Indtjening: \\$324.128.400
    * Budget: \\$79.160.000

* Cluster 3
    * Består af 22 film
    * Profit margin på 2,295073
    * PG-13, ageRestriction_PG
    * Top 3 genre: Adventure, Action, Sci-Fi
    * Udgivelsesår: 2013
    * Spilletid: 126 min
    * imdbScore: 73
    * MetaScore : 69
    * Indtjening: \\$396.846.700
    * Budget: \\$178.454.500

* Cluster 5
    * Består af 17 film
    * Profit margin på 1,084639
    * PG-13, ageRestriction_PG
    * Top 3 genre: Adventure, Action, Fantasy
    * Udgivelsesår: 2012
    * Spilletid: 138 min
    * imdbScore: 68
    * MetaScore : 58
    * Indtjening: \\$264.841.100
    * Budget: \\$249.294.100

In [13]:
movie_data.loc[movie_data['cluster_group']== 14 ]

,year,runtime,imdbScore,metaScore,gross,votes,budget,Action,Adventure,Animation,...,ageRestriction_15,ageRestriction_G,ageRestriction_NC-17,ageRestriction_PG,ageRestriction_PG-13,ageRestriction_R,ageRestriction_TV-MA,ageRestriction_TV-PG,profit_margin,cluster_group
2,2009.0,162.0,78.0,83.0,760507625.0,1091518.0,237000000.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,3.208893,14.0

In [14]:
pd.set_option('display.max_columns', None)
movie_cluster_data

,year,runtime,imdbScore,metaScore,gross,votes,budget,Action,Adventure,Animation,Biography,Comedy,Crime,Drama,Family,Fantasy,History,Horror,Music,Musical,Mystery,Romance,Sci-Fi,Sport,Thriller,War,Western,ageRestriction_15,ageRestriction_G,ageRestriction_NC-17,ageRestriction_PG,ageRestriction_PG-13,ageRestriction_R,ageRestriction_TV-MA,ageRestriction_TV-PG,profit_margin,Counts
cluster_group,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
0.0,2008.925854,105.818862,62.082276,50.361301,3.517561e+07,9.105774e+04,3.249068e+07,0.230569,0.162276,0.047154,0.082276,0.416260,0.187317,0.539512,0.066341,0.078699,0.034472,0.110244,0.036098,0.009106,0.100488,0.185691,0.057561,0.028618,0.167154,0.014634,0.004878,0.00065,0.015285,0.00065,0.129756,0.381138,0.469919,0.002276,0.000325,4.211434,3075
1.0,2010.215517,117.974138,68.732759,60.375000,1.953836e+08,3.633722e+05,1.335323e+08,0.560345,0.706897,0.258621,0.021552,0.336207,0.060345,0.185345,0.150862,0.150862,0.017241,0.021552,0.012931,0.004310,0.030172,0.038793,0.215517,0.004310,0.094828,0.004310,0.004310,0.00000,0.043103,0.00000,0.310345,0.551724,0.094828,0.000000,0.000000,1.744287,232
2.0,2010.500000,122.533333,72.400000,66.433333,3.241284e+08,5.380424e+05,7.916000e+07,0.366667,0.700000,0.300000,0.066667,0.500000,0.033333,0.300000,0.100000,0.233333,0.000000,0.033333,0.000000,0.000000,0.000000,0.066667,0.066667,0.033333,0.033333,0.000000,0.000000,0.00000,0.033333,0.00000,0.366667,0.400000,0.200000,0.000000,0.000000,6.023852,30
3.0,2013.000000,126.181818,73.045455,69.454545,3.968467e+08,4.798184e+05,1.784545e+08,0.636364,1.000000,0.227273,0.000000,0.272727,0.045455,0.090909,0.090909,0.181818,0.000000,0.000000,0.000000,0.000000,0.045455,0.000000,0.409091,0.000000,0.000000,0.000000,0.000000,0.00000,0.090909,0.00000,0.227273,0.681818,0.000000,0.000000,0.000000,2.295073,22
4.0,2015.200000,122.800000,76.200000,71.000000,5.069438e+08,6.676352e+05,1.790000e+08,0.400000,0.600000,0.400000,0.000000,0.400000,0.200000,0.200000,0.200000,0.200000,0.000000,0.000000,0.000000,0.200000,0.000000,0.000000,0.200000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0.600000,0.400000,0.000000,0.000000,0.000000,2.863214,5
5.0,2012.058824,138.647059,68.823529,58.705882,2.648411e+08,4.574424e+05,2.492941e+08,0.764706,0.941176,0.058824,0.000000,0.058824,0.058824,0.000000,0.117647,0.352941,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.411765,0.000000,0.058824,0.000000,0.000000,0.00000,0.000000,0.00000,0.176471,0.823529,0.000000,0.000000,0.000000,1.084639,17
6.0,2016.250000,141.250000,73.250000,63.000000,4.914964e+08,6.720352e+05,2.587500e+08,0.750000,1.000000,0.250000,0.000000,0.000000,0.000000,0.250000,0.000000,0.250000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.250000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0.250000,0.750000,0.000000,0.000000,0.000000,1.898240,4
7.0,2015.000000,130.500000,78.000000,74.500000,6.159306e+08,7.323220e+05,2.100000e+08,1.000000,1.000000,0.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.500000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0.500000,0.500000,0.000000,0.000000,0.000000,2.937999,2
8.0,2019.000000,181.000000,84.000000,78.000000,8.583730e+08,7.181460e+05,3.560000e+08,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,1.000000,0.000000,0.000000,0.000000,2.411160,1
9.0,2018.000000,149.000000,85.000000,68.000000,6.788155e+08,7.745460e+05,3.210000e+08,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,1.000000,0.000000,0.000000,0.000000,2.114690,1
10.0,2018.000000,134.000000,73.000000,88.000000,7.000596e+08,5.814120e+05,2.000000e+08,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,1.000000,0.000000,0.000000,0.000000,3.500298,1
11.0,2017.000000,152.000000,70.000000,84.000000,6.201814e+08,5.386460e+05,3.170000e+08,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,1.000000,0.000000,0.000000,0.000000,1.956408,1
12.0,2015.000000,138.000000,79.000000,80.000000,9.366622e+08,8.374320e+05,2.450000e+08,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,1.000000,0.000000,0.000000,0.000000,3.823111,1
13.0,2015.000000,124.000000,70.000000,59.000000,6.522706e+08,5.633090e+05,1.500000e+08,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,1.000000,0.000000,0.000000,0.000000,4.348471,1
14.0,2009.000000,162.000000,78.000000,83.000000,7.605076e+08,1.091518e+06,2.370000e+08,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,1.000000,0.000000,0.000000,0.000000,3.208893,1